name: CI
run-name: CI for ${{ github.ref }}

on:
  pull_request:
    branches:
      - "ubuntu-*"

jobs:
  pkg-deps:
    name: Package dependencies
    uses: rebornplusplus/chisel-releases/.github/workflows/pkg-deps.yaml@main
