name: CI
run-name: CI for ${{ github.ref }}

on:
  pull_request_target:
    branches:
      - "ubuntu-*"
  pull_request_target:
    branches:
      - "ubuntu-*"

jobs:
  pkg-deps:
    name: Package dependencies
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: "Post PR comment"
        uses: actions/github-script@v6
        with:
          script: |
            const body = 'Diff for ' + context.payload.pull_request.head.sha + ':';
            console.log('Creating new comment...');
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: body,
            });
