name: CI
run-name: CI for ${{ github.ref }}

on:
  push:
    branches:
      - "ubuntu-*"
  pull_request:
    branches:
      - "ubuntu-*"

jobs:
  installability-tests:
    name: Installability tests
    uses: rebornplusplus/chisel-releases/.github/workflows/install-slices.yaml@main

  lint:
    name: Lint
    uses: rebornplusplus/chisel-releases/.github/workflows/lint.yaml@main
