name: "Removed slices"

on:
  push:
    paths:
      - "slices/**"
  pull_request:
    paths:
      - "slices/**"
  workflow_call:

jobs:
  check:
    name: "Check for removed slices"
    runs-on: "ubuntu-latest"
    env:
      files_main: "main-files"
    steps:
      - uses: actions/checkout@v4
        with:
          # We do need to fetch all history for all branches.
          fetch-depth: 0

      - name: "Check for removed slices"
        run: |
          ln -s "${{ env.files_main }}/.github/scripts/removed-slices/removed-slices" .
          # For pull request events, use github.base_ref as the old git ref.
          # For push events, the github.event.before value contains the SHA of
          # the most recent commit on ref before the push.
          git branch -a
          git log ubuntu-22.04
          ls -l
          git diff ubuntu-22.04
